create table "public"."User Table" (
    "id" bigint generated by default as identity not null,
    "username" text not null,
    "email" text,
    "created_at" timestamp without time zone
);


alter table "public"."User Table" enable row level security;

create table "public"."search_logs" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null default gen_random_uuid(),
    "search_term" text,
    "trend_id" uuid default gen_random_uuid(),
    "created_at" timestamp without time zone
);


alter table "public"."search_logs" enable row level security;

create table "public"."trends" (
    "id" uuid not null default gen_random_uuid(),
    "title" text not null,
    "category" text,
    "views" bigint,
    "created_at" timestamp without time zone
);


alter table "public"."trends" enable row level security;

CREATE UNIQUE INDEX "User Table_pkey" ON public."User Table" USING btree (id);

CREATE UNIQUE INDEX search_logs_pkey ON public.search_logs USING btree (id);

CREATE UNIQUE INDEX trends_pkey ON public.trends USING btree (id);

alter table "public"."User Table" add constraint "User Table_pkey" PRIMARY KEY using index "User Table_pkey";

alter table "public"."search_logs" add constraint "search_logs_pkey" PRIMARY KEY using index "search_logs_pkey";

alter table "public"."trends" add constraint "trends_pkey" PRIMARY KEY using index "trends_pkey";

grant delete on table "public"."User Table" to "anon";

grant insert on table "public"."User Table" to "anon";

grant references on table "public"."User Table" to "anon";

grant select on table "public"."User Table" to "anon";

grant trigger on table "public"."User Table" to "anon";

grant truncate on table "public"."User Table" to "anon";

grant update on table "public"."User Table" to "anon";

grant delete on table "public"."User Table" to "authenticated";

grant insert on table "public"."User Table" to "authenticated";

grant references on table "public"."User Table" to "authenticated";

grant select on table "public"."User Table" to "authenticated";

grant trigger on table "public"."User Table" to "authenticated";

grant truncate on table "public"."User Table" to "authenticated";

grant update on table "public"."User Table" to "authenticated";

grant delete on table "public"."User Table" to "service_role";

grant insert on table "public"."User Table" to "service_role";

grant references on table "public"."User Table" to "service_role";

grant select on table "public"."User Table" to "service_role";

grant trigger on table "public"."User Table" to "service_role";

grant truncate on table "public"."User Table" to "service_role";

grant update on table "public"."User Table" to "service_role";

grant delete on table "public"."search_logs" to "anon";

grant insert on table "public"."search_logs" to "anon";

grant references on table "public"."search_logs" to "anon";

grant select on table "public"."search_logs" to "anon";

grant trigger on table "public"."search_logs" to "anon";

grant truncate on table "public"."search_logs" to "anon";

grant update on table "public"."search_logs" to "anon";

grant delete on table "public"."search_logs" to "authenticated";

grant insert on table "public"."search_logs" to "authenticated";

grant references on table "public"."search_logs" to "authenticated";

grant select on table "public"."search_logs" to "authenticated";

grant trigger on table "public"."search_logs" to "authenticated";

grant truncate on table "public"."search_logs" to "authenticated";

grant update on table "public"."search_logs" to "authenticated";

grant delete on table "public"."search_logs" to "service_role";

grant insert on table "public"."search_logs" to "service_role";

grant references on table "public"."search_logs" to "service_role";

grant select on table "public"."search_logs" to "service_role";

grant trigger on table "public"."search_logs" to "service_role";

grant truncate on table "public"."search_logs" to "service_role";

grant update on table "public"."search_logs" to "service_role";

grant delete on table "public"."trends" to "anon";

grant insert on table "public"."trends" to "anon";

grant references on table "public"."trends" to "anon";

grant select on table "public"."trends" to "anon";

grant trigger on table "public"."trends" to "anon";

grant truncate on table "public"."trends" to "anon";

grant update on table "public"."trends" to "anon";

grant delete on table "public"."trends" to "authenticated";

grant insert on table "public"."trends" to "authenticated";

grant references on table "public"."trends" to "authenticated";

grant select on table "public"."trends" to "authenticated";

grant trigger on table "public"."trends" to "authenticated";

grant truncate on table "public"."trends" to "authenticated";

grant update on table "public"."trends" to "authenticated";

grant delete on table "public"."trends" to "service_role";

grant insert on table "public"."trends" to "service_role";

grant references on table "public"."trends" to "service_role";

grant select on table "public"."trends" to "service_role";

grant trigger on table "public"."trends" to "service_role";

grant truncate on table "public"."trends" to "service_role";

grant update on table "public"."trends" to "service_role";


